/* Este arreglo se usa para testear
const preguntas = [
  // REALISTA
  {
    texto: "¿Te gustaría diseñar los planos de una casa o estructura?",
    area: "realista",
  },
  {
    texto:
      "¿Te interesa el funcionamiento de circuitos electrónicos o motores?",
    area: "realista",
  },
];
*/

// Arreglo de preguntas
const preguntas = [
  // REALISTA
  { texto: "¿Te gustaría diseñar los planos de una casa o estructura?", area: "realista" },
  { texto: "¿Te interesa el funcionamiento de circuitos electrónicos o motores?", area: "realista" },
  { texto: "¿Te gusta el trabajo físico o al aire libre (como la agricultura o construcción)?", area: "realista" },
  { texto: "¿Tienes facilidad para armar y desarmar objetos mecánicos?", area: "realista" },
  { texto: "¿Posees destreza manual para usar herramientas de precisión?", area: "realista" },
  { texto: "¿Te orientas con facilidad en mapas, planos y espacios tridimensionales?", area: "realista" },

  // INVESTIGADOR
  { texto: "¿Te genera curiosidad saber cómo funcionan los virus o las células?", area: "investigador" },
  { texto: "¿Te gustaría pasar tiempo en un laboratorio realizando experimentos químicos?", area: "investigador" },
  { texto: "¿Te apasiona investigar el origen de problemas sociales o históricos?", area: "investigador" },
  { texto: "¿Comprendes con rapidez conceptos matemáticos o lógicos complejos?", area: "investigador" },
  { texto: "¿Tienes capacidad para concentrarte largas horas en la lectura científica?", area: "investigador" },
  { texto: "¿Puedes analizar datos estadísticos y sacar conclusiones lógicas de ellos?", area: "investigador" },

  // ARTÍSTICO
  { texto: "¿Disfrutarías escribir artículos de opinión o cuentos literarios?", area: "artistico" },
  { texto: "¿Te atrae la idea de restaurar obras de arte o diseñar vestuarios?", area: "artistico" },
  { texto: "¿Te gustaría tocar un instrumento musical o componer música profesionalmente?", area: "artistico" },
  { texto: "¿Consideras que tienes talento para el dibujo, la pintura o el diseño visual?", area: "artistico" },
  { texto: "¿Puedes usar la creatividad para resolver problemas de manera poco convencional?", area: "artistico" },
  { texto: "¿Tienes facilidad para aprender idiomas o expresarte correctamente de forma escrita?", area: "artistico" },

  // SOCIAL
  { texto: "¿Te sientes cómodo explicando temas complejos a personas que no los entienden?", area: "social" },
  { texto: "¿Sentirías satisfacción trabajando en programas de ayuda comunitaria?", area: "social" },
  { texto: "¿Te interesa aprender sobre primeros auxilios y el cuidado de la salud?", area: "social" },
  { texto: "¿Tienes facilidad de palabra y buen trato con las personas?", area: "social" },
  { texto: "¿Sabes escuchar a los demás y mostrar empatía ante sus problemas?", area: "social" },
  { texto: "¿Te consideras capaz de mantener la calma en situaciones de emergencia médica?", area: "social" },

  // EMPRENDEDOR
  { texto: "¿Te gustaría ser el responsable de dirigir un equipo para alcanzar una meta de ventas?", area: "emprendedor" },
  { texto: "¿Te gustaría convencer a otros sobre la validez de tus ideas o proyectos?", area: "emprendedor" },
  { texto: "¿Te motiva la idea de crear y gestionar tu propia empresa?", area: "emprendedor" },
  { texto: "¿Te resulta fácil delegar tareas y organizar el trabajo de otros?", area: "emprendedor" },
  { texto: "¿Tienes facilidad para la negociación y el manejo de conflictos?", area: "emprendedor" },
  { texto: "¿Tienes capacidad de liderazgo y te sientes cómodo tomando decisiones bajo presión?", area: "emprendedor" },

  // CONVENCIONAL
  { texto: "¿Te agrada llevar un control detallado y ordenado de gastos y facturas?", area: "convencional" },
  { texto: "¿Prefieres trabajar en una oficina con tareas y horarios claramente definidos?", area: "convencional" },
  { texto: "¿Te gusta organizar archivos, documentos y bases de datos?", area: "convencional" },
  { texto: "¿Eres una persona extremadamente minuciosa y detallista con la información?", area: "convencional" },
  { texto: "¿Eres hábil para clasificar y catalogar objetos de forma sistemática?", area: "convencional" },
  { texto: "¿Te sientes cómodo siguiendo procedimientos paso a paso sin desviarte?", area: "convencional" }
];
//

const RIASEC = {
  Realista:
    "Prefieres actividades prácticas y concretas. Te sientes cómodo trabajando con herramientas, máquinas, tecnología o en entornos físicos donde puedes ver resultados tangibles.",

  Investigador:
    "Te gusta analizar, investigar y resolver problemas complejos. Disfrutas aprender cómo funcionan las cosas, trabajar con datos, ciencia y pensamiento lógico.",

  Artistico:
    "Eres creativo y expresivo. Te atraen actividades relacionadas con el arte, el diseño, la música o cualquier forma de expresión original.",

  Social:
    "Te interesa ayudar a los demás y trabajar con personas. Disfrutas enseñar, cuidar, apoyar o colaborar en entornos humanos.",

  Emprendedor:
    "Te gusta liderar, tomar decisiones y generar ideas de negocio. Te atraen las ventas, la gestión, la negociación y los retos competitivos.",

  Convencional:
    "Prefieres el orden, la organización y trabajar con datos o sistemas. Te sientes cómodo siguiendo procesos, administrando información y manteniendo estructuras claras.",
};

const careers = {
  Realista: [
    "INGENIERO AGRONOMO",
    "LICENCIATURA EN MEDICINA VETERINARIA Y ZOOTECNIA",
    "INGENIERIA CIVIL",
    "INGENIERIA EN LOGISTICA Y TRANSPORTE",
    "INGENIERIA EN TOPOGRAFIA GEOMATICA",
    "INGENIERIA INDUSTRIAL",
    "INGENIERIA MECANICA ELECTRICA",
    "INGENIERIA ROBOTICA",
    "LICENCIATURA EN INGENIERIA EN ALIMENTOS Y BIOTECNOLOGIA",
    "LICENCIATURA EN INGENIERIA EN CIENCIA DE MATERIALES",
    "LICENCIATURA EN INGENIERIA EN ELECTROMOVILIDAD Y AUTOTRONICA",
    "LICENCIATURA EN INGENIERIA EN ELECTRONICA Y SISTEMAS INTELIGENTES",
    "LICENCIATURA EN INGENIERIA EN MECATRONICA INTELIGENTE",
    "INGENIERIA EN BIOTECNOLOGIA",
    "INGENIERIA MECATRONICA DUAL",
    "INGENIERIA AGROINDUSTRIAL",
    "INGENIERIA EN SISTEMAS PECUARIOS",
    "TECNICO SUPERIOR UNIVERSITARIO EN PRODUCCION Y SANIDAD AVICOLA",
    "INGENIERIA EN ROBOTICA Y AUTOMATIZACION",
    "LICENCIATURA EN AGROBIOTECNOLOGIA",
    "INGENIERIA MECATRONICA",
    "INGENIERIA QUIMICA",
    "INGENIERIA CIVIL",
    "INGENIERIA EN TELEMATICA",
    "INGENIERO AGRONOMO",
    "INGENIERIA DE PROCESOS Y COMERCIO INTERNACIONAL",
    "INGENIERIA MECATRONICA",
    "LICENCIATURA EN INGENIERIA EN OBRAS Y SERVICIOS",
    "LICENCIATURA EN INGENIERIA EN RECURSOS NATURALES Y AGROPECUARIOS",
    "TECNICO SUPERIOR UNIVERSITARIO EN ELECTRONICA Y MECANICA AUTOMOTRIZ",
    "INGENIERIA BIOQUIMICA",
    "INGENIERIA INDUSTRIAL",
    "INGENIERIA MECANICA ELECTRICA",
    "INGENIERIA MECATRONICA",
    "INGENIERIA MECANICA ELECTRICA",
    "LICENCIATURA EN INGENIERIA EN MANEJO DE RECURSOS NATURALES",
    "INGENIERIA EN SISTEMAS BIOLOGICOS",
    "LICENCIATURA EN AGROBIOTECNOLOGIA",
    "LICENCIATURA EN MEDICINA VETERINARIA Y ZOOTECNIA",
    "INGENIERIA EN ENERGIA",
    "INGENIERIA EN SISTEMAS BIOLOGICOS",
    "INGENIERIA MECATRONICA",
    "LICENCIATURA EN INGENIERIA EN AUTOMATIZACION INDUSTRIAL",
  ],

  Investigador: [
    "LICENCIATURA EN BIOLOGIA",
    "LICENCIATURA EN CIENCIA DE LOS ALIMENTOS",
    "LICENCIATURA EN CIENCIAS BIOMEDICAS",
    "INGENIERIA FOTONICA",
    "INGENIERIA BIOMEDICA",
    "INGENIERIA QUIMICA",
    "LICENCIATURA EN FISICA",
    "LICENCIATURA EN MATEMATICAS",
    "LICENCIATURA EN QUIMICA",
    "LICENCIATURA EN QUIMICO FARMACEUTICO BIOLOGO",
    "LICENCIATURA EN BIOQUIMICA CLINICA Y MEDICINA DE LABORATORIO",
    "LICENCIATURA EN CIENCIAS BIOMEDICAS",
    "LICENCIATURA EN CIENCIAS FORENSES",
    "LICENCIATURA EN CIBERSEGURIDAD",
    "LICENCIATURA EN INTELIGENCIA ARTIFICIAL Y CIENCIA DE LOS DATOS",
    "LICENCIATURA EN TECNOLOGIAS BIOMEDICAS",
    "INGENIERIA BIOMEDICA",
    "INGENIERIA EN COMPUTACION",
    "INGENIERIA EN DESARROLLO DE SOFTWARE",
    "INGENIERIA EN COMPUTACION",
    "INGENIERIA MECATRONICA",
    "INGENIERIA QUIMICA",
    "LICENCIATURA EN QUIMICO FARMACEUTICO BIOLOGO",
    "INGENIERIA EN COMPUTACION",
    "INGENIERIA EN TELEMATICA",
    "LICENCIATURA EN BIOLOGIA",
    "LICENCIATURA EN INGENIERIA EN COMUNICACION MULTIMEDIA",
    "LICENCIATURA EN BIOLOGIA MARINA",
    "INGENIERIA EN ELECTRONICA Y COMPUTACION",
    "INGENIERIA EN ELECTRONICA Y COMPUTACION",
    "INGENIERIA EN GEOFISICA",
    "INGENIERIA EN TELEMATICA",
    "INGENIERIA EN CIENCIAS COMPUTACIONALES",
    "INGENIERIA EN NANOTECNOLOGIA",
    "INGENIERIA EN DISEÑO MOLECULAR DE MATERIALES",
    "INGENIERIA EN ELECTRONICA Y COMPUTACION",
    "INGENIERIA EN SISTEMAS BIOLOGICOS",
    "LICENCIATURA EN QUIMICO FARMACEUTICO BIOLOGO",
  ],

  Artistico: [
    "LICENCIATURA EN ARQUITECTURA",
    "LICENCIATURA EN DISEÑO DE INTERIORES Y AMBIENTACION",
    "LICENCIATURA EN DISEÑO DE MODAS",
    "LICENCIATURA EN DISEÑO INDUSTRIAL",
    "LICENCIATURA EN DISEÑO PARA LA COMUNICACION GRAFICA",
    "LICENCIATURA EN DISEÑO, ARTE Y TECNOLOGIAS INTERACTIVAS",
    "LICENCIATURA EN MUSICA CON ORIENTACION EN CANTO",
    "LICENCIATURA EN MUSICA CON ORIENTACION EN COMPOSICION",
    "LICENCIATURA EN MUSICA CON ORIENTACION EN DIRECCION CORAL",
    "LICENCIATURA EN MUSICA CON ORIENTACION EN EJECUTANTE",
    "LICENCIATURA EN MUSICA CON ORIENTACION EN PEDAGOGIA MUSICAL",
    "PROGRAMA BASICO MUSICAL",
    "TECNICO EN MUSICA",
    "LICENCIATURA EN ARTES ESCENICAS PARA LA EXPRESION DANCISTICA",
    "LICENCIATURA EN ARTES ESCENICAS PARA LA EXPRESION TEATRAL",
    "LICENCIATURA EN ARTES VISUALES PARA LA EXPRESION FOTOGRAFICA",
    "LICENCIATURA EN ARTES VISUALES PARA LA EXPRESION PLASTICA",
    "LICENCIATURA EN ESCRITURA CREATIVA",
    "LICENCIATURA EN CREATIVIDAD DIGITAL",
    "INGENIERIA EN ANIMACION Y TECNOLOGIAS CREATIVAS",
    "LICENCIATURA EN GESTION DE INDUSTRIAS CULTURALES Y CREATIVAS",
    "INGENIERIA EN DISEÑO INDUSTRIAL",
    "INGENIERIA EN VIDEOJUEGOS",
    "LICENCIATURA EN ARQUITECTURA",
    "LICENCIATURA EN ARTES VISUALES PARA LA EXPRESION FOTOGRAFICA",
    "LICENCIATURA EN ARTES VISUALES PARA LA EXPRESION PLASTICA",
    "LICENCIATURA EN DISEÑO PARA LA COMUNICACION GRAFICA",
    "LICENCIATURA EN ARTES ( ESCOLARIZADA )",
    "INGENIERIA EN VIDEOJUEGOS",
    "LICENCIATURA EN ARQUITECTURA",
    "LICENCIATURA EN DISEÑO DE ARTESANIA",
    "LICENCIATURA EN HISTORIA DEL ARTE",
  ],

  Social: [
    "LICENCIATURA EN CIRUJANO DENTISTA",
    "LICENCIATURA EN ATENCION PREHOSPITALARIA Y GESTION DE RIESGOS",
    "LICENCIATURA EN CULTURA FISICA Y DEPORTES",
    "LICENCIATURA EN ENFERMERIA",
    "LICENCIATURA EN ENFERMERIA (NIVELACION)",
    "LICENCIATURA EN NUTRICION",
    "LICENCIATURA EN PODOLOGIA",
    "LICENCIATURA EN PSICOLOGIA",
    "LICENCIATURA EN RADIOLOGIA E IMAGEN",
    "LICENCIATURA EN TERAPIA FISICA",
    "LICENCIATURA EN TERAPIA FISICA (NIVELACION)",
    "LICENCIATURA EN TERAPIA RESPIRATORIA",
    "MEDICO CIRUJANO Y PARTERO",
    "TECNICO SUPERIOR UNIVERSITARIO EN EMERGENCIAS SEGURIDAD LABORAL Y RESCATES (NIVELACION)",
    "TECNICO SUPERIOR UNIVERSITARIO EN PROTESIS DENTAL",
    "LICENCIATURA EN CIRUJANO DENTISTA",
    "LICENCIATURA EN ENFERMERIA",
    "LICENCIATURA EN NUTRICION",
    "LICENCIATURA EN PSICOLOGIA",
    "LICENCIATURA EN TERAPIA FISICA",
    "MEDICO CIRUJANO Y PARTERO",
    "LICENCIATURA EN CIRUJANO DENTISTA",
    "LICENCIATURA EN ENFERMERIA",
    "LICENCIATURA EN ENFERMERIA (NIVELACION)",
    "LICENCIATURA EN NUTRICION",
    "LICENCIATURA EN PSICOLOGIA",
    "LICENCIATURA EN QUIMICO FARMACEUTICO BIOLOGO",
    "MEDICO CIRUJANO Y PARTERO",
    "LICENCIATURA EN ENFERMERIA",
    "LICENCIATURA EN GERONTOLOGIA",
    "LICENCIATURA EN PSICOLOGIA DE LA SALUD COMUNITARIA",
    "LICENCIATURA EN ENFERMERIA (NIVELACION)",
    "LICENCIATURA EN ENFERMERIA",
    "LICENCIATURA EN PSICOLOGIA",
    "LICENCIATURA EN QUIMICO FARMACEUTICO BIOLOGO",
    "MEDICO CIRUJANO Y PARTERO",
    "LICENCIATURA EN PSICOLOGIA",
    "LICENCIATURA EN CULTURA FISICA Y DEPORTES",
    "LICENCIATURA EN ENFERMERIA",
    "LICENCIATURA EN NUTRICION",
    "LICENCIATURA EN PSICOLOGIA",
    "MEDICO CIRUJANO Y PARTERO",
    "LICENCIATURA EN ENFERMERIA",
    "LICENCIATURA EN NUTRICION",
    "LICENCIATURA EN ENFERMERIA (NIVELACION)",
    "LICENCIATURA EN PSICOLOGIA",
    "LICENCIATURA EN PSICOLOGIA",
    "LICENCIATURA EN ENFERMERIA",
    "LICENCIATURA EN ENFERMERIA (NIVELACION)",
    "LICENCIATURA EN NUTRICION",
    "LICENCIATURA EN PSICOLOGIA",
    "LICENCIATURA EN CIRUJANO DENTISTA",
    "LICENCIATURA EN CULTURA FISICA Y DEPORTES",
    "LICENCIATURA EN ENFERMERIA",
    "LICENCIATURA EN NUTRICION",
    "LICENCIATURA EN PSICOLOGIA",
    "LICENCIATURA EN SEGURIDAD LABORAL, PROTECCION CIVIL Y EMERGENCIAS",
    "LICENCIATURA EN TRABAJO SOCIAL",
    "MEDICO CIRUJANO Y PARTERO",
    "LICENCIATURA EN CIENCIAS FORENSES",
    "LICENCIATURA EN ENFERMERIA",
    "LICENCIATURA EN GERONTOLOGIA",
    "LICENCIATURA EN NUTRICION",
    "LICENCIATURA EN SALUD PUBLICA",
    "MEDICO CIRUJANO Y PARTERO",
    "LICENCIATURA EN ENFERMERIA",
    "LICENCIATURA EN GERONTOLOGIA",
    "LICENCIATURA EN NUTRICION",
    "LICENCIATURA EN PSICOLOGIA",
    "LICENCIATURA EN QUIMICO FARMACEUTICO BIOLOGO",
    "MEDICO CIRUJANO Y PARTERO",
  ],

  Emprendedor: [
    "LICENCIATURA EN AGRONEGOCIOS",
    "INGENIERIA EN NEGOCIOS",
    "LICENCIATURA EN ADMINISTRACION",
    "LICENCIATURA EN ADMINISTRACION FINANCIERA Y SISTEMAS",
    "LICENCIATURA EN ADMINISTRACION GUBERNAMENTAL Y POLITICAS PUBLICAS",
    "LICENCIATURA EN AUDITORIA Y CONTABILIDAD GUBERNAMENTAL",
    "LICENCIATURA EN CONTADURIA PUBLICA",
    "LICENCIATURA EN ECONOMIA",
    "LICENCIATURA EN GESTION DE NEGOCIOS GASTRONOMICOS",
    "LICENCIATURA EN GESTION Y ECONOMIA AMBIENTAL",
    "LICENCIATURA EN MERCADOTECNIA",
    "LICENCIATURA EN NEGOCIOS INTERNACIONALES",
    "LICENCIATURA EN RECURSOS HUMANOS",
    "LICENCIATURA EN RELACIONES PUBLICAS Y COMUNICACION",
    "LICENCIATURA EN TURISMO",
    "LICENCIATURA EN MERCADOTECNIA DIGITAL",
    "LICENCIATURA EN INTELIGENCIA FINANCIERA Y DE NEGOCIOS",
    "LICENCIATURA EN ADMINISTRACION DE LAS ORGANIZACIONES",
    "LICENCIATURA EN GESTION CULTURAL",
    "INGENIERIA EN NEGOCIOS",
    "LICENCIATURA EN ADMINISTRACION",
    "LICENCIATURA EN NEGOCIOS INTERNACIONALES",
    "LICENCIATURA EN ADMINISTRACION",
    "LICENCIATURA EN CONTADURIA PUBLICA",
    "LICENCIATURA EN NEGOCIOS INTERNACIONALES",
    "LICENCIATURA EN NEGOCIOS SOSTENIBLES",
    "LICENCIATURA EN ADMINISTRACION",
    "LICENCIATURA EN AGRONEGOCIOS",
    "LICENCIATURA EN ADMINISTRACION",
    "LICENCIATURA EN CONTADURIA PUBLICA",
    "LICENCIATURA EN MERCADOTECNIA",
    "LICENCIATURA EN NEGOCIOS INTERNACIONALES",
    "LICENCIATURA EN RECURSOS HUMANOS",
    "LICENCIATURA EN ADMINISTRACION",
    "LICENCIATURA EN CONTADURIA PUBLICA",
    "LICENCIATURA EN ADMINISTRACION",
    "LICENCIATURA EN CIENCIAS Y ARTES CULINARIAS",
    "LICENCIATURA EN CONTADURIA PUBLICA",
    "LICENCIATURA EN TURISMO",
    "LICENCIATURA EN ADMINISTRACION",
    "LICENCIATURA EN ADMINISTRACION",
    "LICENCIATURA EN ADMINISTRACION FINANCIERA Y SISTEMAS",
    "LICENCIATURA EN CONTADURIA PUBLICA",
    "LICENCIATURA EN TURISMO",
    "LICENCIATURA EN ADMINISTRACION",
    "LICENCIATURA EN INGENIERIA EN ADMINISTRACION INDUSTRIAL",
    "LICENCIATURA EN ADMINISTRACION",
    "LICENCIATURA EN ADMINISTRACION",
    "LICENCIATURA EN AGRONEGOCIOS",
    "LICENCIATURA EN CONTADURIA PUBLICA",
    "LICENCIATURA EN DESARROLLO TURISTICO",
    "LICENCIATURA EN AGRONEGOCIOS",
    "LICENCIATURA EN DESARROLLO TURISTICO SUSTENTABLE",
    "LICENCIATURA EN NEGOCIOS INTERNACIONALES",
    "LICENCIATURA EN ADMINISTRACION DE NEGOCIOS",
    "LICENCIATURA EN CONTADURIA PUBLICA",
    "LICENCIATURA EN ADMINISTRACION",
    "LICENCIATURA EN AGRONEGOCIOS",
    "LICENCIATURA EN CONTADURIA PUBLICA",
    "LICENCIATURA EN TURISMO",
  ],

  Convencional: [
    "LICENCIATURA EN URBANISTICA Y MEDIO AMBIENTE",
    "LICENCIATURA EN TECNOLOGIAS DE LA INFORMACION",
    "TECNICO SUPERIOR UNIVERSITARIO EN TECNOLOGIAS DE LA INFORMACION",
    "INGENIERIA EN COMPUTACION",
    "INGENIERIA INFORMATICA",
    "LICENCIATURA EN MATEMATICAS",
    "TECNICO SUPERIOR UNIVERSITARIO EN SISTEMAS INFORMATICOS",
    "LICENCIATURA EN DESARROLLO DE SISTEMAS WEB",
    "LICENCIATURA EN TECNOLOGIAS E INFORMACION",
    "ABOGADO",
    "ABOGADO (SEMIESCOLARIZADO)",
    "LICENCIATURA EN ANTROPOLOGIA",
    "LICENCIATURA EN CRIMINOLOGIA",
    "LICENCIATURA EN DIDACTICA DEL FRANCES COMO LENGUA EXTRANJERA",
    "LICENCIATURA EN DOCENCIA DEL INGLES COMO LENGUA EXTRANJERA",
    "LICENCIATURA EN ESTUDIOS POLITICOS Y GOBIERNO",
    "LICENCIATURA EN FILOSOFIA",
    "LICENCIATURA EN GEOGRAFIA",
    "LICENCIATURA EN HISTORIA",
    "LICENCIATURA EN LETRAS HISPANICAS",
    "LICENCIATURA EN RELACIONES INTERNACIONALES",
    "LICENCIATURA EN SOCIOLOGIA",
    "LICENCIATURA EN TRABAJO SOCIAL",
    "LICENCIATURA EN TRABAJO SOCIAL (NIVELACION)",
    "LICENCIATURA EN BIBLIOTECOLOGIA Y GESTION DEL CONOCIMIENTO",
    "LICENCIATURA EN DESARROLLO EDUCATIVO",
    "LICENCIATURA EN PERIODISMO DIGITAL",
    "LICENCIATURA EN SEGURIDAD CIUDADANA",
    "ABOGADO",
    "INGENIERIA INFORMATICA",
    "LICENCIATURA EN CIENCIAS AMBIENTALES Y DEL TERRITORIO",
    "LICENCIATURA EN CONSTRUCCION DE LA PAZ Y SEGURIDAD",
    "ABOGADO",
    "ABOGADO",
    "ABOGADO",
    "LICENCIATURA EN CIUDADES SOSTENIBLES",
    "ABOGADO",
    "ABOGADO",
    "INGENIERIA INDUSTRIAL",
    "INGENIERIA INFORMATICA",
    "LICENCIATURA EN PERIODISMO",
    "ABOGADO",
    "ABOGADO",
    "LICENCIATURA EN HUMANIDADES",
    "LICENCIATURA EN LENGUAS Y CULTURAS EXTRANJERAS",
    "ABOGADO (SEMIESCOLARIZADO)",
    "ABOGADO",
    "LICENCIATURA EN EDUCACION",
    "LICENCIATURA EN EDUCACION INDIGENA",
    "ABOGADO",
    "LICENCIATURA EN LETRAS HISPANICAS",
    "LICENCIATURA EN PERIODISMO",
    "ABOGADO",
    "LICENCIATURA EN ESTUDIOS LIBERALES",
    "ABOGADO",
    "LICENCIATURA EN EDUCACION",
    "LICENCIATURA EN TECNOLOGIAS DE LA INFORMACION",
    "LICENCIATURA EN TRABAJO SOCIAL",
  ],
};

/*
const careers = {
  Realista: [
    "Ingeniero agronomo",
    "Licenciatura en urbanistica y medio ambiente",
    "Licenciatura en agronegocios",
    "Licenciatura en ciencia de los alimentos",
    "Licenciatura en medicina veterinaria y zootecnia",
    "Ingenieria civil",
    "Ingenieria en logistica y transporte",
    "Ingenieria en topografia geomatica",
    "Ingenieria industrial",
    "Ingenieria mecanica electrica",
    "Ingenieria robotica",
    "Licenciatura en ingenieria en alimentos y biotecnologia",
    "Licenciatura en ingenieria en ciencia de materiales",
    "Licenciatura en ingenieria en electromovilidad y autotronica",
    "Licenciatura en ingenieria en electronica y sistemas inteligentes",
    "Licenciatura en ingenieria en mecatronica inteligente",
    "Ingenieria en biotecnologia",
    "Ingenieria mecatronica dual",
    "Ingenieria agroindustrial",
    "Ingenieria en sistemas pecuarios",
    "Tecnico superior universitario en electronica y mecanica automotriz",
    "Tecnico superior universitario en produccion y sanidad avicola",
  ],

  Investigador: [
    "Licenciatura en biologia",
    "Licenciatura en ciencias biomedicas",
    "Licenciatura en bioquimica clinica y medicina de laboratorio",
    "Licenciatura en ciencias forenses",
    "Licenciatura en fisica",
    "Licenciatura en matematicas",
    "Licenciatura en quimica",
    "Licenciatura en quimico farmaceutico biologo",
    "Licenciatura en inteligencia artificial y ciencia de los datos",
    "Licenciatura en ciberseguridad",
    "Ingenieria fotonica",
    "Ingenieria biomedica",
    "Ingenieria quimica",
    "Ingenieria en nanotecnologia",
    "Ingenieria en geofisica",
    "Ingenieria en sistemas biologicos",
    "Ingenieria en diseño molecular de materiales",
    "Ingenieria en ciencias computacionales",
    "Ingenieria en energia",
  ],

  Artistico: [
    "Licenciatura en arquitectura",
    "Licenciatura en diseño de interiores y ambientacion",
    "Licenciatura en diseño de modas",
    "Licenciatura en diseño industrial",
    "Licenciatura en diseño para la comunicacion grafica",
    "Licenciatura en diseño, arte y tecnologias interactivas",
    "Licenciatura en musica con orientacion en canto",
    "Licenciatura en musica con orientacion en composicion",
    "Licenciatura en musica con orientacion en direccion coral",
    "Licenciatura en musica con orientacion en ejecutante",
    "Licenciatura en musica con orientacion en pedagogia musical",
    "Programa basico musical",
    "Tecnico en musica",
    "Licenciatura en artes escenicas para la expresion dancistica",
    "Licenciatura en artes escenicas para la expresion teatral",
    "Licenciatura en artes visuales para la expresion fotografica",
    "Licenciatura en artes visuales para la expresion plastica",
    "Licenciatura en escritura creativa",
    "Licenciatura en historia del arte",
    "Licenciatura en diseño de artesania",
    "Licenciatura en creatividad digital",
    "Ingenieria en animacion y tecnologias creativas",
    "Ingenieria en videojuegos",
    "Licenciatura en artes ( escolarizada )",
  ],

  Social: [
    "Licenciatura en cirujano dentista",
    "Licenciatura en atencion prehospitalaria y gestion de riesgos",
    "Licenciatura en cultura fisica y deportes",
    "Licenciatura en enfermeria",
    "Licenciatura en enfermeria (nivelacion)",
    "Licenciatura en nutricion",
    "Licenciatura en podologia",
    "Licenciatura en psicologia",
    "Licenciatura en radiologia e imagen",
    "Licenciatura en terapia fisica",
    "Licenciatura en terapia fisica (nivelacion)",
    "Licenciatura en terapia respiratoria",
    "Medico cirujano y partero",
    "Tecnico superior universitario en emergencias seguridad laboral y rescates (nivelacion)",
    "Tecnico superior universitario en protesis dental",
    "Licenciatura en gerontologia",
    "Licenciatura en salud publica",
    "Licenciatura en psicologia de la salud comunitaria",
  ],

  Emprendedor: [
    "Ingenieria en negocios",
    "Licenciatura en administracion",
    "Licenciatura en administracion financiera y sistemas",
    "Licenciatura en administracion gubernamental y politicas publicas",
    "Licenciatura en auditoria y contabilidad gubernamental",
    "Licenciatura en contaduria publica",
    "Licenciatura en economia",
    "Licenciatura en gestion de negocios gastronomicos",
    "Licenciatura en gestion y economia ambiental",
    "Licenciatura en mercadotecnia",
    "Licenciatura en negocios internacionales",
    "Licenciatura en recursos humanos",
    "Licenciatura en relaciones publicas y comunicacion",
    "Licenciatura en turismo",
    "Licenciatura en mercadotecnia digital",
    "Licenciatura en inteligencia financiera y de negocios",
    "Licenciatura en administracion de las organizaciones",
    "Licenciatura en gestion cultural",
    "Licenciatura en negocios sostenibles",
    "Licenciatura en desarrollo turistico",
    "Licenciatura en desarrollo turistico sustentable",
    "Licenciatura en administracion de negocios",
  ],

  Convencional: [
    "Licenciatura en tecnologias de la informacion",
    "Tecnico superior universitario en tecnologias de la informacion",
    "Tecnico superior universitario en sistemas informaticos",
    "Licenciatura en desarrollo de sistemas web",
    "Licenciatura en tecnologias e informacion",
    "Ingenieria en computacion",
    "Ingenieria informatica",
    "Licenciatura en periodismo digital",
    "Licenciatura en bibliotecologia y gestion del conocimiento",
    "Licenciatura en desarrollo educativo",
    "Licenciatura en seguridad ciudadana",
    "Abogado",
    "Abogado (semiescolarizado)",
    "Licenciatura en antropologia",
    "Licenciatura en criminologia",
    "Licenciatura en didactica del frances como lengua extranjera",
    "Licenciatura en docencia del ingles como lengua extranjera",
    "Licenciatura en estudios politicos y gobierno",
    "Licenciatura en filosofia",
    "Licenciatura en geografia",
    "Licenciatura en historia",
    "Licenciatura en letras hispanicas",
    "Licenciatura en relaciones internacionales",
    "Licenciatura en sociologia",
    "Licenciatura en trabajo social",
    "Licenciatura en trabajo social (nivelacion)",
    "Licenciatura en periodismo",
    "Licenciatura en educacion",
    "Licenciatura en educacion indigena",
    "Licenciatura en humanidades",
    "Licenciatura en lenguas y culturas extranjeras",
    "Licenciatura en estudios liberales",
  ],
};
*/