// Arreglo de preguntas
const preguntas = [
    {texto: "¿Te gustaría diseñar los planos de una casa o estructura?"},
    {texto: "¿Te genera curiosidad saber cómo funcionan los virus o las células?"},
    {texto: "¿Disfrutarías escribir artículos de opinión o cuentos literarios?"},
    {texto: "¿Te sientes cómodo explicando temas complejos a personas que no los entienden?"},
    {texto: "¿Te gustaría ser el responsable de dirigir un equipo para alcanzar una meta de ventas?"},
    {texto: "¿Te agrada llevar un control detallado y ordenado de gastos y facturas?"},
    {texto: "¿Te interesa el funcionamiento de circuitos electrónicos o motores?"},
    {texto: "¿Te gustaría pasar tiempo en un laboratorio realizando experimentos químicos?"},
    {texto: "¿Te atrae la idea de restaurar obras de arte o diseñar vestuarios?"},
    {texto: "¿Sentirías satisfacción trabajando en programas de ayuda comunitaria?"},
    {texto: "¿Te gustaría convencer a otros sobre la validez de tus ideas o proyectos?"},
    {texto: "¿Prefieres trabajar en una oficina con tareas y horarios claramente definidos?"},
    {texto: "¿Te gusta el trabajo físico o al aire libre (como la agricultura o construcción)?"},
    {texto: "¿Te apasiona investigar el origen de problemas sociales o históricos?"},
    {texto: "¿Te gustaría tocar un instrumento musical o componer música profesionalmente?"},
    {texto: "¿Te interesa aprender sobre primeros auxilios y el cuidado de la salud?"},
    {texto: "¿Te motiva la idea de crear y gestionar tu propia empresa?"},
    {texto: "¿Te gusta organizar archivos, documentos y bases de datos?"},
    {texto: "¿Tienes facilidad para armar y desarmar objetos mecánicos?"},
    {texto: "¿Comprendes con rapidez conceptos matemáticos o lógicos complejos?"},
    {texto: "¿Consideras que tienes talento para el dibujo, la pintura o el diseño visual?"},
    {texto: "¿Tienes facilidad de palabra y buen trato con las personas?"},
    {texto: "¿Te resulta fácil delegar tareas y organizar el trabajo de otros?"},
    {texto: "¿Eres una persona extremadamente minuciosa y detallista con la información?"},
    {texto: "¿Posees destreza manual para usar herramientas de precisión?"},
    {texto: "¿Tienes capacidad para concentrarte largas horas en la lectura científica?"},
    {texto: "¿Puedes usar la creatividad para resolver problemas de manera poco convencional?"},
    {texto: "¿Sabes escuchar a los demás y mostrar empatía ante sus problemas?"},
    {texto: "¿Tienes facilidad para la negociación y el manejo de conflictos?"},
    {texto: "¿Eres hábil para clasificar y catalogar objetos de forma sistemática?"},
    {texto: "¿Te orientas con facilidad en mapas, planos y espacios tridimensionales?"},
    {texto: "¿Puedes analizar datos estadísticos y sacar conclusiones lógicas de ellos?"},
    {texto: "¿Tienes facilidad para aprender idiomas o expresarte correctamente de forma escrita?"},
    {texto: "¿Te consideras capaz de mantener la calma en situaciones de emergencia médica?"},
    {texto: "¿Tienes capacidad de liderazgo y te sientes cómodo tomando decisiones bajo presión?"},
];
